# Generated by Django 3.2.3 on 2021-06-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nomUsuario', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('correo', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
