# Generated by Django 3.2.3 on 2021-06-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriacompra_compras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaCompra',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
