# Generated by Django 3.2.3 on 2021-06-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210616_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCompra',
            fields=[
                ('idpelicula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de pelicula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('pelicula', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Pelicula')),
                ('entradas', models.IntegerField(verbose_name='Cant_entradas')),
                ('correocompra', models.CharField(max_length=60, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=19, verbose_name='Telefono')),
                ('nrotarjeta', models.IntegerField(verbose_name='Nrotarjeta')),
                ('anno', models.IntegerField(verbose_name='anno')),
                ('mes', models.IntegerField(verbose_name='mes')),
                ('nroverificador', models.IntegerField(verbose_name='nroverificador')),
                ('nombrecompra', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidocompra', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccioncompra', models.CharField(max_length=100, verbose_name='Direccion')),
                ('codigopostal', models.IntegerField(verbose_name='Codigopostal')),
            ],
        ),
    ]
