# Generated by Django 3.2.3 on 2021-06-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoriacompra_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('foto', models.ImageField(upload_to='photos', verbose_name='foto')),
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nombre')),
                ('sinopsis', models.TextField(verbose_name='sinopsis')),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=60, primary_key=True, serialize=False, verbose_name='Correo'),
        ),
    ]
