# Generated by Django 3.2.3 on 2021-06-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_peliculacreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='peliculaCreate',
        ),
    ]
